### PR TITLE
Simplify setup.py and require Cython.

### PR DESCRIPTION
**Pull request by jameshilliard**
I got #41 working as a buildroot package building directly from git. I moved all the gitignore changes to the one in the root directory.
Config.in:
```
config BR2_PACKAGE_PYTHON_ADBUS
	bool "python-adbus"
	depends on BR2_PACKAGE_PYTHON3
	select BR2_PACKAGE_PYTHON3_PYEXPAT # runtime
	select BR2_PACKAGE_HOST_PYTHON_CYTHON
	help
	  D-Bus Binding for Python that supports coroutines (asyncio).

	  https://github.com/ccxtechnologies/adbus
```
python-adbus.mk:
```
################################################################################
#
# python-adbus
#
################################################################################

PYTHON_ADBUS_VERSION = 37209eb3e3198f244fc8c8596434c99e92139608
PYTHON_ADBUS_SITE = $(call github,jameshilliard,adbus,$(PYTHON_ADBUS_VERSION))
PYTHON_ADBUS_SETUP_TYPE = setuptools
PYTHON_ADBUS_LICENSE = MIT
PYTHON_ADBUS_LICENSE_FILES = LICENSE
PYTHON_ADBUS_DEPENDENCIES += host-python-cython

$(eval $(python-package))
```

### CODE REVIEW

**Comment by charleseidsness** [comment]
We really appreciate your interest and enthusiasm for this project, and I'm glad you got it working with buildroot for you, but we really can't change this.

We absolutely require a record of the c file that is generated by cython that we use to build our system, this is a hard requirement for us. We also have a custom rebuild system on top of buildroot that uses the additional options that we provided in the setup.py file.

If you can't use the setup.py as-is we could try to find a way that works for everyone, but we really can't remove features from our build system.

**Comment by jameshilliard** [comment]
> We absolutely require a record of the c file that is generated by cython that we use to build our system, this is a hard requirement for us.

Do you need to record the c file so that you can follow backtraces/core dumps?

> If you can't use the setup.py as-is we could try to find a way that works for everyone, but we really can't remove features from our build system.

It works fine either way for me.

**Comment by charleseidsness** [comment]
Yes, in case there are any bugs introduced in the conversion to C, but since you're the second person that asked I think I can bring this is in a way that doesn't break what we're doing. Instead of asking you to make changes on your branch I'll merge this in, and then make some updates to it.

We have another location that we can store that file that I'll look at.

**Comment by charleseidsness** [comment]
We'll see if we can bring in the spirit of this PR in a way that doesn't break our build system. A new commit will come soon if we can get it work.

**Pull request closed without merging**
