### PR TITLE
Rework build system and enable travis

### PR DESCRIPTION
**Pull request by jameshilliard**
This seems to work for me, hopefully this doesn't break your build system.

I've attempted to make it so that cython is only required when installing from git and not when installing from pypi although I haven't tested that extensively.

### CODE REVIEW

**Comment by charleseidsness** [comment]
It looks safe, but we'll have a closer look early next week before merging.

**Comment by jameshilliard** [comment]
I think you probably also need to enable travis in the repo settings.

**Comment by charleseidsness** [comment]
I think I added it, we don't use travis so if there is something else I need to set let me know.

**Comment by jameshilliard** [comment]
I don't see any builds [here](https://travis-ci.com/ccxtechnologies/adbus). I think you need to activate the github apps integration as described [here](https://travis-ci.com/getting_started).

**Comment by charleseidsness** [comment]
I went through the process earlier, but maybe for .org, not .com ... I tried again at .com will have another look in a week if that didn't do it.

**Pull request merged**
